import type { Metadata } from 'next';
import './globals.scss';
import Header from '@/components/header/Header';
import Wrapper from '@/components/wrapper/Wrapper';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main>
          <Wrapper>{children}</Wrapper>
        </main>
      </body>
    </html>
  );
}
